### ISSUE TITLE
Add enums for tag test values.

### ISSUE THREAD

**Issue by abvg9** [notaphplover/catan-heroes#20]

**Comment by notaphplover** [comment]
It's not possible. The `@Tag` annotation expects a constant expression as value:

![java_err_test_enum](https://user-images.githubusercontent.com/16786032/77819976-3a847a80-70df-11ea-91df-dcf915a232ad.png)
`The value for annotation attribute Tag.value must be a constant expression`

I'm afraid there is no way to use an enum 's value as a constant expression

**Comment by abvg9** [comment]
> It's not possible. The `@Tag` annotation expects a constant expression as value:
> 
> ![java_err_test_enum](https://user-images.githubusercontent.com/16786032/77819976-3a847a80-70df-11ea-91df-dcf915a232ad.png)
> `The value for annotation attribute Tag.value must be a constant expression`
> 
> I'm afraid there is no way to use an enum 's value as a constant expression

Did you try to use toString() ?

**Comment by notaphplover** [comment]
> > It's not possible. The `@Tag` annotation expects a constant expression as value:
> > ![java_err_test_enum](https://user-images.githubusercontent.com/16786032/77819976-3a847a80-70df-11ea-91df-dcf915a232ad.png)
> > `The value for annotation attribute Tag.value must be a constant expression`
> > I'm afraid there is no way to use an enum 's value as a constant expression
> 
> Did you try to use toString() ?

@abvg9  Yes, but it was a waste of time, method calls are not considered constant expressions

**Comment by abvg9** [comment]
Maybe you can add some functuionality in the enums to return a constant string. Did you tried?

**Comment by notaphplover** [comment]
@abvg9 Yes. If you think it's possible a PR would be more than welcomed

**Comment by notaphplover** [comment]
After looking in StackOverflow I found [this](https://stackoverflow.com/questions/54336977/use-enum-values-as-a-tag-in-junit-5). Seems a bit excesive.

**Comment by abvg9** [comment]
[Here](https://www.baeldung.com/java-immutable-maps) you have an example to create a  Unmodifiable or Immutable maps. Based on the article, I think it would be best to use a variable of immutable type
