### ISSUE TITLE
Consider adopting CQRS

### ISSUE THREAD

**Issue by notaphplover** [notaphplover/catan-heroes#41]
- Catan game engine has a native and ugly implementation of command handlers.
- The editable board reindex its production map when an structure is built.
- The point calculator could be faster with a cache strategy based on adjusting points when a board element is built or upgraded.

All this facts demands a CQRS pattern.

Consider using Axon messaging.

**Comment by notaphplover** [comment]
@abvg9 any thoughts about this?

**Comment by abvg9** [comment]
I have no experience with Axon and CQRS, so ... enlighten me ^^

**Comment by notaphplover** [comment]
Consider [this](https://medium.com/eleven-labs/cqrs-pattern-c1d6f8517314) a brief introduction.

Basically it's a pattern to apply a kind event oriented programming.

**Comment by abvg9** [comment]
As the blog said: "_One of the main con is to convince the members of a team that its benefits justify the additional complexity of this solution, as underlines the excellent article called CQRS Journey (see below)_." Would there be great benefits in implementing this complex system? 
I leave the answer in your hands

**Comment by notaphplover** [comment]
It seems it won't be necessary, closed.
