### ISSUE TITLE
Implement a trade system

### ISSUE THREAD

**Issue by notaphplover** [notaphplover/catan-heroes#43]
A trade system must be implemented in order to allow clients to trade resources.

- Only player to player trades must be implemented.
- Only the active player can perform a trade request.

Trade requests details are the following ones:

- A trade request contains the desired resources.
- A trade request contains the collection of acceptable trades.

It would be reasonable to use a wildcard value in order to reduce the size of the acceptable trades collection.

**Comment by abvg9** [comment]
The point 'A trade request contains the collection of acceptable trades' it's a very good idea,  but 'Only player to player trades must be implemented' this one ... I think that players must be able to send in one order an offer to multiple players.

**Comment by notaphplover** [comment]
> The point 'A trade request contains the collection of acceptable trades' it's a very good idea, but 'Only player to player trades must be implemented' this one ... I think that players must be able to send in one order an offer to multiple players.

What I wanted to express is that no automatic trades are allowed. For example, a trade using a port wouldn't be allowed.

**Comment by abvg9** [comment]
Ok then i agree.
