### ISSUE TITLE
Simplify CatanBoard

### ISSUE THREAD

**Issue by notaphplover** [notaphplover/catan-heroes#44]
CatanBoard and CatanEditableBoard must be a single class.
The logic to store the production must be moved to a new class ProductionManager

**Comment by notaphplover** [comment]
@abvg9 Any thoughts about this?

**Comment by abvg9** [comment]
What is the purpose of this modification?

**Comment by notaphplover** [comment]
Simplify the project's models.

I just realice that clients need to perform game simulations. Keeping that in mind, there is no point in having a read only board. With no need and no purpose it's better to have just one board class. This would allow us to remove the `TBoard` generic at `ICatanGame`
