### ISSUE TITLE
Add new exception to check equality of elements

### ISSUE THREAD

**Issue by abvg9** [notaphplover/catan-heroes#47]
In line 112 at the file src/com/ucm/dasi/catan/board/CatanBoard.java it's recommended to implement a runtime expcetion to handle this situation.

**Comment by notaphplover** [comment]
@abvg9 InvalidBoardElementException seems to be the right one, should this exception be a RuntimeException?

Keep in mind that it's not mandatory to place a throws clause if a runtime exception is thrown, so it is still possible to place the throws clause when needed.

**Comment by notaphplover** [comment]
@abvg9 Try to reference code with GitHub references in base of a certain commit. For example, the line you are referencing is [this one](https://github.com/notaphplover/catan-heroes/blob/ce2c00d7259c2d34ffd403128a0e07ea16b3b02b/src/com/ucm/dasi/catan/board/CatanBoard.java#L112)

**Comment by abvg9** [comment]
> @abvg9 InvalidBoardElementException seems to be the right one, should this exception be a RuntimeException?
> 
> Keep in mind that it's not mandatory to place a throws clause if a runtime exception is thrown, so it is still possible to place the throws clause when needed.

Okay, a runtime be said.
